### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by aneelac22**
Update Patternfly, React, testing-library

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
When I start the app locally, I get this error:

```sh
ERROR in ./src/Components/SampleComponent/sample-component.test.tsx:9:39
TS2339: Property 'toHaveTextContent' does not exist on type 'JestMatchers<HTMLElement>'.
     7 |
     8 |   render(<SampleComponent>{children}</SampleComponent>);
  >  9 |   expect(screen.getByRole('heading')).toHaveTextContent('Hello');
       |                                       ^^^^^^^^^^^^^^^^^
    10 | });

```

We should address that.

There is also an absolute crap ton of dependencies that we don't seem to need anymore. Can you go trough both dev and normal dependencies and clean it up please?

**Comment by aneelac22** [comment]
I updated everything that can be, stylelint's need to be updated in frontend-components before doing it here and all of the dependencies left seems to be needed

**Comment by Hyperkid123** [comment]
I think we can just ditch style lint.

**Review by Hyperkid123 — CHANGES_REQUESTED** [review]
There are plenty more changes we can do:

1. Entirely remove babel (it is no longer required)
2. Use ts-jest for testing with babel gone: https://kulshekhar.github.io/ts-jest/docs/getting-started/installation
3. remove style lint and the script
4. remove `@pmmmwh/react-refresh-webpack-plugin` as it should be installed by the common config
5. The `_unstableHotReload` has been renamed to `hotReload`
6. The `prop-types` dependency is useless for TS builds

**Comment by Andrewgdewar** [comment]
> There are plenty more changes we can do:
> 
> 1. Entirely remove babel (it is no longer required)
> 2. Use ts-jest for testing with babel gone: https://kulshekhar.github.io/ts-jest/docs/getting-started/installation

Removing Babel does not seem to be an option with the current build of frontend-components. 
Attempting the same thing as this PR accomplishes now on a mature application, and the configuration for jest has blocked for days. 
Without babel I get a ton of issues, the only way I can get even half of my tests passing is to have a transform and babel installed.
  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!@redhat-cloud-services|@openshift|lodash-es|uuid)',
  ],

**Comment by Hyperkid123** [comment]
@Andrewgdewar so far we have been able to remove babel on our side on projects that only use TS. The `transformIgnorePatterns` is still unfortunately required because of the dynamic plugin SDK dependency and its dependencies. Something that we will address I hope soon.

I hope I can find some time to check your PR and see what the issue might be with removing Babel. Ts-jest should be good enough to fully replace. After all, it's just a different transpiler.

**Comment by Hyperkid123** [comment]
@Andrewgdewar I am gonna go and change the plugin SDK to stop using `lodash-es`. The SDK itself can be transformed by adding a `'node_modules/@openshift/dynamic-plugin-sdk/dist/index.js': 'ts-jest',` transform option

**Comment by Andrewgdewar** [comment]
> @Andrewgdewar once this https://issues.redhat.com/browse/RHCLOUD-28614 is resolved and all PRs are closed, new version of the frontend components should be released and the issue and requirement for babel should go away.

Awesome! 
When that happens I'll update and attempt a purge of babel! 😎

**Comment by Hyperkid123** [comment]
@Andrewgdewar new packages should be already released.

**Comment by Andrewgdewar** [comment]
> @Andrewgdewar new packages should be already released.

I attempted to update to the latest version of frontend-components and remove babel, but the "SkeletonTable" is now causing a number of test failures.

Likely related to ESM modules. 

If you want to attempt to play around with it yourself, my base branch is [here](https://github.com/content-services/content-sources-frontend/pull/148). 
You don't need to run the service, just the tests to see the issues if you do update fec/remove babel.

Maybe theres something in my jest.config or tsconfig that I am missing, although I did attempt to change a few things with both to get it running.

Thoughts?

**Comment by Hyperkid123** [comment]
> I attempted to update to the latest version of frontend-components and remove babel, but the "SkeletonTable" is now causing a number of test failures.

The skeleton table is most likely not related to the removal of babel but to its migration to a different repository. @fhlavac is leading that effort and can help you out there.

**Comment by fhlavac** [comment]
@Andrewgdewar we have already migrated SkeletonTable https://github.com/patternfly/react-component-groups so preferably use it from the new location. So far there are no changes in the frontend-components repository so I don't think the errors are caused by the migration effort. A PR deprecating the old component should be up in a day or two. If you have any more questions, let me know :slightly_smiling_face:

**Review by karelhala — APPROVED** [review]

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
